language: csharp
mono: none
dotnet: 1.0.0
cache:
  directories:
    - packages
sudo: required
services:
  - docker
before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL
script:
  - make
  - make all-the-dockers
  - make docker-push
after_success:
  - make docker-tag
  - make docker-push
