language: csharp
cache:
  directories:
    - packages
sudo: required
services:
  - docker
before_install:
  - mkdir -p ./packages
  - wget -O ./packages/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL
script:
  - make compile test
  - make all-the-dockers
  - make docker-push
after_success:
  - make docker-tag
  - make docker-push
