Description: "Serial Number Example Application"
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  targetCluster:
    Type: String
    Description: "ECS Cluster name to be deployed on"
  dockerTag:
    Type: String
    Description: "Docker tag to deploy"

Resources:
  ecsServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow everything to ecs service
      VpcId: vpc-b4bce5d1
      SecurityGroupIngress:
        - IpProtocol: '-1'
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  taskDefinitionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: 
                - "ecs-tasks.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
          - PolicyName: "readandwritedynamodbsequences"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:GetItem"
                    - "dynamodb:PutItem"
                  Resource: !ImportValue serialnumberexample-persistence-sequences-table-arn

  taskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      TaskRoleArn: !GetAtt taskDefinitionRole.Arn
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: serial-number-example
          Image: !Sub docker.io/bazwilliams/serial-number-example:${dockerTag}
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: sequencesTableName
              Value: !ImportValue serialnumberexample-persistence-sequences-table-name

  service:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref targetCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref taskDefinition
#       Role: !Ref ecsServiceRole
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
          - !Ref ecsServiceSecurityGroup
          Subnets:
          - subnet-24d1891e
          - subnet-d8e86081
      LoadBalancers:
        - ContainerName: serial-number-example
          ContainerPort: 8080
          TargetGroupArn: !ImportValue serialnumberexample-targetgroup-arn