Description: "ECS Cluster"
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  clusterName:
    Type: String
    Description: "The name of our ECS cluster"

Resources:
  ecsCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref clusterName
